# Generated by Django 2.2 on 2021-03-14 02:01

from django.db import migrations, models
import inventory.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=15, unique=True)),
                ('cant', models.CharField(max_length=7)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to=inventory.utils.upload_file_name, validators=[inventory.utils.validate_file])),
                ('cant_rows', models.CharField(editable=False, max_length=6)),
                ('cant_products', models.CharField(editable=False, max_length=15)),
                ('average_price_products', models.CharField(editable=False, max_length=18)),
            ],
        ),
    ]
